### ISSUE TITLE
Enable to add extra HTTP headers

### ISSUE THREAD

**Issue by yu-iskw** [bnjns/terraform-provider-metabase#44]
### Description
We can protect self-hosted metabase on Google Cloud Kubernetes Engine with Google Cloud IAP. When we call REST APIs through Cloud IAP, we need to add a ID token with the `Authorization` header. 

https://cloud.google.com/iap/docs/authentication-howto
```bash
curl --verbose --header 'Authorization: Bearer ID_TOKEN' URL
```

### New or Affected Resource(s)
NA

### Potential Terraform Configuration

```hcl
provider "metabase" {
  host     = local.metabase_credentials["host"]
  username = local.metabase_credentials["username"]
  password = local.metabase_credentials["password"]
  headers = {
     Authorizer = "Bearer: ${var.id_token}"
  }
}
```

### References
- https://cloud.google.com/iap/docs/authentication-howto

**Comment by bnjns** [comment]
Hi @yu-iskw, thanks for raising the suggestion! Very much in favour of this - I'll take a look as soon as I can 🙂
